--- #YAML:1.0
name:               Nitesi-DBI
version:            0.0031
abstract:           DBI bundle for Nitesi shop machine
author:
    - Stefan Hornburg (Racke) <racke@linuxia.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Nitesi:               0.002
    SQL::Abstract:        0
    SQL::Abstract::More:  0
    Test::Database:       0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
